[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agent-examples"
version = "0.1.0"
description = "Google ADK Agent Examples"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = ["mcp", "robin-stocks"]

[tool.hatch.build.targets.wheel]
packages = ["GoogleADK", "scripts"]